# This is a basic workflow to help you get started with Actions

name: pcb_fabrication_outputs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate_fabrication_outputs:
    runs-on: ubuntu-18.04
    container: setsoft/kicad_auto:ki6

    steps:
    - uses: actions/checkout@v3

    - name: Quick Start
      run: |
        kibot --quick-start
        
    - name: Retrieve results
      uses: actions/upload-artifact@v2
      with:
        name: Automatic_outputs
        path: Generated
